### ISSUE TITLE
Hold Up

### ISSUE THREAD

**Issue by MEEPofFaith** [NUCLEAR-BOMB/Inverse#1]
You copied [HappyGingerWolf/Inverted-Machines](https://github.com/HappyGingerWolf/Inverted-Machines), didn't you?

**Comment by Slotterleet** [comment]
Not sure if he even knew that mod existed lol

**Comment by ddmitv** [comment]
I saw some mod about 3-4 years ago about inverted blocks and decided to make my own mod about it. Anyway this is not a real project, just a test project.
